#!/usr/bin/env bash

pushd $(dirname "$0") >/dev/null

source .conf

target="objects.mk"

cofc
trunc "${target}"
printf "EXT_OBJ = " >> "${target}"
cof extern -prf ${bin}/extern. >> "${target}"
printf "\nOBJ = " >> "${target}"
cof src -prf ${bin}/ >> "${target}"
printf "\nobjects := \$(OBJ) \$(EXT_OBJ)\n" >> "${target}"

popd >/dev/null
